include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
